services:

  postgres:
    image: postgres:15
    container_name: postgres_f1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: formula1
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./SQL/combined:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 2g

  spark:
    image: bitnami/spark:latest
    container_name: spark_f1
    environment:
      - SPARK_MODE=master
      - SPARK_CLASSPATH=/opt/jars/postgresql-42.7.5.jar
      - SPARK_SUBMIT_OPTIONS=--jars /opt/jars/postgresql-42.7.5.jar
    ports:
      - "8080:8080"  # Spark Web UI
    volumes:
      - ../transform_and_load:/opt/spark_jobs
      - ../datalake:/data
      - ./drivers/postgresql-42.7.5.jar:/opt/jars/postgresql-42.7.5.jar
    deploy:
      resources:
        limits:
          memory: 3g

  python_runner:
    image: python:3.10-slim
    container_name: python_f1
    volumes:
      - ../ingestion_scripts:/app
      - ../datalake:/data
      - ./scripts:/housekeeping
    working_dir: /app
    command: sh -c "python /housekeeping/install_missing_modules.py && tail -f /dev/null"
    deploy:
      resources:
        limits:
          memory: 512m

volumes:
  pgdata:
